# Generated by Django 4.2.2 on 2023-08-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fisrt_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("time_log", models.TimeField()),
            ],
        ),
    ]
